# prettier-ignore
# yaml-language-server: $schema=https://raw.githubusercontent.com/idefant/nerd-startpage/main/config.schema.json

# -----------------------------------------------------------------------------
# Nerd Startpage — config.yaml
#
# Важно:
# - Если поле/секция ОТСУТСТВУЕТ — применяется значение по умолчанию из схемы.
# - Если секция есть, но внутри нет полей — для полей тоже применятся дефолты.
# - В некоторых полях дефолты отличаются от дефолтов секции. Перезаписанные
#   дефолты указаны в комментариях
# - Чтобы переопределить дефолт: раскомментируй строку и задай своё значение.
# -----------------------------------------------------------------------------

# -----------------------------------------------------------------------------
# columns — параметры сетки категорий/колонок
#
# Опции сетки:
#   gap — расстояние между колонками       (default: 24)
#   width — ширина колонки                 (default: 200)
#   maxCount — максимум колонок на экране  (default: 6)
# -----------------------------------------------------------------------------
columns:
  # gap: 24
  # width: 200
  # maxCount: 6

# -----------------------------------------------------------------------------
# defaultMode — режим по умолчанию
# Доступные значения — это ключи в секции modes: google|yandex|npm|history|...
# -----------------------------------------------------------------------------
# defaultMode: google

# -----------------------------------------------------------------------------
# leaderKey — “лидер-клавиша” для leaderSequence
# Пример: leaderKey=":" и leaderSequence="ip" → вводишь ":ip"
# -----------------------------------------------------------------------------
# leaderKey: ':'

# -----------------------------------------------------------------------------
# editConfigUrl — URL для редактирования конфига
# -----------------------------------------------------------------------------
# editConfigUrl: ""

# -----------------------------------------------------------------------------
# modes — режимы (каждый режим имеет один и тот же набор опций)
#
# Доступные режимы: google, yandex, npm, history, bookmarks, sessions, links,
# commandPalette
#
# Опции режима:
#   hotkey: string | string[]                (default: [])
#   leaderSequence: string | string[]        (default: [])
#   showInCommandPalette: boolean            (default: true)
#   disabled: boolean                        (default: false)
# -----------------------------------------------------------------------------
modes:
  google:
    # hotkey: 'ctrl+g'
  yandex:
    # hotkey: 'ctrl+y'
  npm:
    # showInCommandPalette: false
  history:
    # hotkey: 'ctrl+h'
  bookmarks:
    # hotkey: 'ctrl+b'
  sessions:
    # hotkey: 'ctrl+s'
  links:
    # hotkey: 'ctrl+f'
  commandPalette:
    # showInCommandPalette: false
    # hotkey: 'ctrl+p'

# -----------------------------------------------------------------------------
# commands — команды (каждый команда имеет один и тот же набор опций)
#
# Доступные команды: nextSuggestion, prevSuggestion, clearInput,
# openLinkFromClipboard, openGoogle, openYandex, searchOnGoogleFromClipboard,
# searchOnYandexFromClipboard, editConfig, showConfig, reloadConfig,
# setConfigUrlFromClipboard, showMyIP
#
# Опции команд:
#   hotkey: string | string[]                (default: [])
#   leaderSequence: string | string[]        (default: [])
#   showInCommandPalette: boolean            (default: true)
#   disabled: boolean                        (default: false)
# -----------------------------------------------------------------------------
commands:
  nextSuggestion:
    # hotkey: 'ArrowDown'
    # showInCommandPalette: false
  prevSuggestion:
    # hotkey: 'ArrowUp'
    # showInCommandPalette: false
  clearInput:
    # hotkey: 'ctrl+l'
    # showInCommandPalette: false
  openLinkFromClipboard:
  openGoogle:
  openYandex:
  searchOnGoogleFromClipboard:
  searchOnYandexFromClipboard:
  editConfig:
  showConfig:
  reloadConfig:
  setConfigUrlFromClipboard:
  showMyIP:
    leaderSequence: 'ip'
    # service: 'ifconfig'

# -----------------------------------------------------------------------------
# categories — список категорий с ссылками (default: [])
#
# Структура:
# categories:
#   - name: string
#     color: white|red|orange|yellow|green|lightGreen|lightBlue|blue|violet|pink
#     links:
#       - name: string
#         icon: optional string
#         url: валидный URL
#         alias: optional string (короткий алиас)
# -----------------------------------------------------------------------------
categories:
  - name:  About_Project
    color: orange
    links:
      - { name: README.md, icon: , url: https://github.com/idefant/nerd-startpage, alias: gh }
      - { name: My_Github_Profile, icon: , url: https://github.com/idefant }
      - { name: My_Website, icon: 󰖟, url: https://idefant.ru }
  - name:  Social
    color: blue
    links:
      - { name: Telegram, icon: , url: https://web.telegram.org/, alias: tg }
      - { name: Youtube, icon: , url: https://youtube.com/, alias: yt }
      - { name: Gmail, icon: 󰊫, url: https://mail.google.com/, alias: gm }
      - { name: LinkedIn, icon: , url: https://linkedin.com, alias: li }
      - { name: WhatsApp, icon: , url: https://web.whatsapp.com/, alias: wa }
  - name:  Code
    color: green
    links:
      - { name: NPM, icon: , url: https://www.npmjs.com/, alias: npm }
      - { name: BundlePhobia, icon: , url: https://bundlephobia.com/, alias: bp }
      - { name: CanInclude, url: https://caninclude.glitch.me/, alias: ci }
      - { name: CanIUse, url: https://caniuse.com/, alias: cu }
      - { name: Codewars, icon: 󰅩, url: https://www.codewars.com, alias: cw }
  - name: 󱁤 Tools
    color: red
    links:
      - { name: Excalidraw, icon: 󰽉, url: https://excalidraw.com, alias: ew }
      - { name: GDrive, icon: , url: https://drive.google.com/ }
  - name:  Music
    color: lightBlue
    links:
      - { name: Music_For_Programming, url: https://musicforprogramming.net/, alias: mp }
